import 'pinturas.dart';

class HomeController {
  late List<Pintura> pinturas;

  HomeController() {
    pinturas = [
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "Girl with a Pearl Earring", artista: "Johannes Vermeer"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "Girl with a Pearl Earring", artista: "Johannes Vermeer"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "Girl with a Pearl Earring", artista: "Johannes Vermeer"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "The Last Supper", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Persistence of Memory", artista: "Salvador Dalí"),
      Pintura(nome: "Whistler's Mother", artista: "James McNeill Whistler"),
      Pintura(nome: "The Night Watch", artista: "Rembrandt"),
      Pintura(nome: "The Birth of Venus", artista: "Sandro Botticelli"),
      Pintura(nome: "Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Mona Lisa", artista: "Leonardo da Vinci"),
      Pintura(nome: "The Scream", artista: "Edvard Munch"),
      Pintura(nome: "American Gothic", artista: "Grant Wood"),
      Pintura(nome: "Water Lilies", artista: "Claude Monet"),
      Pintura(nome: "The Starry Night", artista: "Vincent van Gogh"),
      Pintura(nome: "Guernica", artista: "Pablo Picasso"),
    ];
  }
}
